# Generated by Django 5.2.1 on 2025-05-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='doctors/')),
                ('specialty', models.CharField(max_length=255)),
                ('conditions', models.CharField(max_length=255)),
                ('memberships', models.TextField(help_text="Har bir a'zolikni vergul bilan ajrating.")),
                ('schedule_mon_tue', models.CharField(default='08:30 - 18:30', max_length=50)),
                ('schedule_wed_thu', models.CharField(default='08:30 - 18:30', max_length=50)),
                ('schedule_fri', models.CharField(default='08:30 - 18:30', max_length=50)),
                ('schedule_sat', models.CharField(default='08:30 - 18:30', max_length=50)),
                ('biography', models.TextField()),
                ('education', models.TextField(help_text='Har bir ta’lim bandini yangi qatordan yozing.')),
                ('research_interests', models.TextField()),
                ('awards', models.TextField(help_text='Har bir mukofotni yangi qatordan yozing.')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('pinterest', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Kasb nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('date', models.DateField(verbose_name='Sana')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.doctor', verbose_name='Shifokor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profession', verbose_name='Kasbi'),
        ),
    ]
