# Generated by Django 5.2.1 on 2025-05-11 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('muallif', models.CharField(max_length=100)),
                ('sana', models.DateField(auto_now_add=True)),
                ('matn', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='blog_rasmlar/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('matn', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.blogpost')),
            ],
        ),
    ]
