# Generated by Django 5.2.1 on 2025-05-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_comment_post_delete_blogpost_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('muallif', models.CharField(max_length=100)),
                ('sana', models.DateField(auto_now_add=True)),
                ('matn', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='blog_rasmlar/')),
            ],
        ),
    ]
