# Generated by Django 5.2.1 on 2025-05-12 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('sayt', models.URLField(blank=True, null=True)),
                ('matn', models.TextField()),
                ('yaratilgan_vaqti', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izohlar', to='main.blogpost')),
            ],
        ),
    ]
